apiVersion: v1
kind: Service
metadata:
  name: solarwind-web
  labels:
    app: solarwind-web
spec:
  type: NodePort
  ports:
  - name: solarwind-web
    port: 3003
    targetPort: 3003
  selector:
    app: solarwind-web